apiVersion: v1
baseDomain: pnayak.org
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: pn-portworx-demo
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWYxZDJkYjA1YjgyNDM1Njk5NGFkY2UzYzU5NmIwMjc6UURMM0U4T0hDMTRJR1c5RlZPMjI3QkFYODdaOThXSVNaNkFEQzVKODc5MTVDTDEwRkNFV0hVQVhSNVhaSUI2Ng==","email":"nayak.p@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWYxZDJkYjA1YjgyNDM1Njk5NGFkY2UzYzU5NmIwMjc6UURMM0U4T0hDMTRJR1c5RlZPMjI3QkFYODdaOThXSVNaNkFEQzVKODc5MTVDTDEwRkNFV0hVQVhSNVhaSUI2Ng==","email":"nayak.p@gmail.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTIxZDhmZDA1LTFlY2EtNDI4Mi1hMmRiLWVlY2Y3MzMyNzA1YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPV0kwWVRFMU9HVXpNMk0wT1dVMk9EZ3dZVFZrWTJNeE5UVXhPR1U0TmlKOS5MWWk0WXJmc1hCaUQ1YlFBRTJBemFsZFlKZURlY2drRUpLN1l1VnVGZmFsYUlBQjV3V3FYRnVtV1pDZ1JsVjlJVlJfMjItTGpQTVczV1hjb1FaYjRlZER0bnR4OUw5VzY1ZnE3bDJYNjRKUzh0dmRpX2N0QXBLVjBiTEl1a2dwaEZsZnJQdHlXV1ZIa3JESlUyVDkzcGhPclZsMGttd0RXOEhweEZvSWRHYjhIdkpNTzJDbjdSYmU3OTBpR1ZSWjhrb1NLclZJM29Fa1pGSm0xZkJJREVBMVBYbHhUdTFVZWhLakNydzRucjlsNmRQRG90S0thQ08tbElRczV5U3M5RlYxcUpkNWx3ZDFubVZqS2xWMTQ4Ti1WUkYzeGJhNEc1SFlaUU9IbjFBNU5XSFo0ampxYTIxZXFsbDRPMUlHdllLZDN5QkpUVG5CX2o1ZGpPTDRTOGk2RkVRdW5PLWt2NGlOZWU3SkQyQ2w1UzYweGlXVGtSakpxR0dKOFNZU3dBQXZTaW1wd1dhYzM4Y0VKTS1yamFCbGJzY0JzQlktclJ1RW03cUpTVEFtd2xBRXhnV3hUeUF1VzR1VS15TlRfTzV4dzJWUkFlVE5UQy11Z2NYX0E5VmxHOVRGVDZTb1Fac0RzY3plZEw0UzkyaW50VzJ6Vm11c3lEUDItZnBlU0VCRllTeUJaNWNNYWM4bTdURVhNUDVWNV9nQnA4eVJ1Nl9tbkRGMVF4dkJoTGowLXo3NUw1MjdYNVVielZ0Y1B6Y1RTX2NHM3JLZUhaLWFOajBhSTFXX1lhRjlpTi1aYVdyZnJNQS1jOUpwMTRwenBxNG42dzA3dVp1LXVaWXhBRjQtN3FoUlE3Q2pmWmgxaUQ5NFVBbTdCUzg0TnZjUE11aV9rVWEtOEcwSQ==","email":"nayak.p@gmail.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTIxZDhmZDA1LTFlY2EtNDI4Mi1hMmRiLWVlY2Y3MzMyNzA1YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPV0kwWVRFMU9HVXpNMk0wT1dVMk9EZ3dZVFZrWTJNeE5UVXhPR1U0TmlKOS5MWWk0WXJmc1hCaUQ1YlFBRTJBemFsZFlKZURlY2drRUpLN1l1VnVGZmFsYUlBQjV3V3FYRnVtV1pDZ1JsVjlJVlJfMjItTGpQTVczV1hjb1FaYjRlZER0bnR4OUw5VzY1ZnE3bDJYNjRKUzh0dmRpX2N0QXBLVjBiTEl1a2dwaEZsZnJQdHlXV1ZIa3JESlUyVDkzcGhPclZsMGttd0RXOEhweEZvSWRHYjhIdkpNTzJDbjdSYmU3OTBpR1ZSWjhrb1NLclZJM29Fa1pGSm0xZkJJREVBMVBYbHhUdTFVZWhLakNydzRucjlsNmRQRG90S0thQ08tbElRczV5U3M5RlYxcUpkNWx3ZDFubVZqS2xWMTQ4Ti1WUkYzeGJhNEc1SFlaUU9IbjFBNU5XSFo0ampxYTIxZXFsbDRPMUlHdllLZDN5QkpUVG5CX2o1ZGpPTDRTOGk2RkVRdW5PLWt2NGlOZWU3SkQyQ2w1UzYweGlXVGtSakpxR0dKOFNZU3dBQXZTaW1wd1dhYzM4Y0VKTS1yamFCbGJzY0JzQlktclJ1RW03cUpTVEFtd2xBRXhnV3hUeUF1VzR1VS15TlRfTzV4dzJWUkFlVE5UQy11Z2NYX0E5VmxHOVRGVDZTb1Fac0RzY3plZEw0UzkyaW50VzJ6Vm11c3lEUDItZnBlU0VCRllTeUJaNWNNYWM4bTdURVhNUDVWNV9nQnA4eVJ1Nl9tbkRGMVF4dkJoTGowLXo3NUw1MjdYNVVielZ0Y1B6Y1RTX2NHM3JLZUhaLWFOajBhSTFXX1lhRjlpTi1aYVdyZnJNQS1jOUpwMTRwenBxNG42dzA3dVp1LXVaWXhBRjQtN3FoUlE3Q2pmWmgxaUQ5NFVBbTdCUzg0TnZjUE11aV9rVWEtOEcwSQ==","email":"nayak.p@gmail.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCg/k+5ucAexMjGfe5lOIvrNJWcdQwlhQ8Ya83WvMk4enE+1dRi9x+mBfCYD127N7s5dApJmSpsZSo83bKyuvmZHmNzYaP8l+idYPV3JNZ9aMa1KIWTRUntflwg6jD0kOPKpDRLgwKbpFf0QBQxzxpZngnRGT0xGHwmPDuYNdyFtsr32WNv/n4y6PFQvShrHzyI6u4/mjRQk+7g+8neY4ElqM8Yh1da5J61QhP1L4N2BvHWsf3NoV7GqF79LWk2cGVHgbCVMMA+v2DcBm+K33NSTPOQRQiZl2ljoVlZuN28wEAw/3iMuyVo+5o09CsR08WEqxM4m6yx3RW1DCBPbHuvDk5svCDC9DBzyeOeNYXbgp2FtpvTyYxMhq0I9GLp8vLIsawjC7xdf6zZToa6mRVxSN0niKgDgg8FKWGwoo360bDUQcvIjP/m9fSTiTeq25+IKmupqGIH8dfw43cuV9aL8YoPrArjqDPvzc9/Ay09BCez3Bjr47LNTSpQhivh7H0= pnayak@Panchaleswars-MacBook-Pro.local
